### ISSUE TITLE
Cannot 'Flush' entry when eof is not known

### ISSUE THREAD

**Issue by ghost** [CTrabant/fdzipstream#1]
Using a posix system there is no means to determine if end-of-file has been reached until a subsequent read returns 0. The zs_entrydata(..) function however needs to know the data is the last chunk via the 'flush' parameter. This is not possible without some feof() like function, even more of an issue if the data is just a stream and a timeout is used instead too!

At present there is only one nasty workaround which is to have two read buffers. We load data into the first, then if the second one fails then we know we have eof.

A better solution may be to allow a zero sized write which would flush the entry:

 zs_entrydata( zstream, zentry, 0, 0, true, &writestatus); //< flush the end of the entry

Better still a function to do the above:

 zs_entryflush( zstream, zentry );

**Comment by CTrabant** [comment]
Excellent suggestion @Crog, thanks for pointing out this limitation.  I will work on implementing your suggestions as soon as I have a spare moment.
