### ISSUE TITLE
zs_writedata() doesn't handle partial writes correctly

### ISSUE THREAD

**Issue by ghost** [CTrabant/fdzipstream#2]
When writing to a named pipe it is common that we incur resource limitations which mean that a write() operation may only partially complete for whatever reason.

The offending code @line 829 needs to be modified as outlined later on:

Before:

``` c
if ( lwritestatus != writelen ) //< A partial write occured, its not actually an error, we should retry instead
{
  return lwritestatus;
}
```

After:

``` c
if ( lwritestatus <= 0 ) //Or just check != -1
{
   return written; //< Doesn't really matter what is returned here it appears but the amountactually complete makes most sense
}

zstream->WriteOffset += lwritestatus;      
written += lwritestatus;
```

**Comment by CTrabant** [comment]
@Crog I left the return value as lwritestatus in the fix as the rest of the functions promise to return the return value of write() when it reports errors.  Of course, on a POSIX system that's always -1 so a bit silly, but I deemed it too much change to transform the meaning at this point.

Thanks for the feedback.  Hopefully you've found this project useful.
